.TH tcplog 8 "JUN 1998" Linux "System Manuals"
.SH NAME
tcplog \- TCP packet logger.

.SH SYNOPSIS
.B tcplog
[-f, --file
.I filename
] [-n, --no-resolve] [-v, --version]

.SH DESCRIPTION

.B tcplog
, a TCP packet logger, is a part of the
.B jail
(just another ip logger) package.

tcplog is a small (daemon) process which logs all TCP connection requests
to the local host. The syslog level at which a given packet is logged is
configurable depending on the destination port. Packets from specific hosts
can be ignored, and a default log level can be specified.

tcplog can be useful in detecting attempted denials of service, and
monitoring network traffic, especially when used in conjunction with
.B icmplog(8).

The configuration is explained in the
.B tcplog.conf(5)
manual page.

.SH OPTIONS
.IP "-f, --file [ filename ]"
Use
.I filename
as the configuration file instead of the default
.I (/etc/tcplog.conf).
.IP "-n, --no-resolve"
Do not resolve IP addresses to hostnames.
.IP "-v, --version"
Display
.B tcplog(8)
version.

.SH "SEE ALSO"
.B tcplog.conf(5), icmplog(8), icmplog.conf(5), syslogd(8)

.SH DISTRIBUTION
jail is distributed under the Artistic License.

.SH AUTHOR
Abhijit Menon-Sen <ams@wiw.org>

$Id: tcplog.8,v 1.7 2001/02/19 10:06:17 ams Exp $
